In [1]:
import myelin_extraction
import imageryclient as ic
import pandas as pd
from caveclient import CAVEclient
from classifiers import SimpleClassifier
import pickle

#for debugging
import importlib

In [2]:
client = CAVEclient('minnie65_public')
# client.materialize.get_versions()
client.version = 1507 #1507, 1412...

img_client = ic.ImageryClient(client=client)

In [3]:
neurons_df = client.materialize.query_table("allen_v1_column_types_slanted_ref")
cell_type_df = client.materialize.query_table('aibs_metamodel_celltypes_v661')
merged_df = pd.merge(neurons_df, cell_type_df, on='pt_root_id', how='inner')
proof_df = client.materialize.tables.proofreading_status_and_strategy(status_axon="t").query(
    select_columns=['pt_root_id','status_axon','status_dendrite','strategy_axon','strategy_dendrite'],
)
merged_df = pd.merge(merged_df, proof_df, on='pt_root_id', how='inner')
final_df = merged_df[['pt_root_id', 'cell_type_x', 'strategy_axon', 'strategy_dendrite']]

ax_full_extend_df = final_df.query("strategy_axon == 'axon_fully_extended'")

#remove all entries from ax_full_extend_df where cell_type_x = 'BC'ArithmeticError
ax_full_extend_df = ax_full_extend_df.query("cell_type_x != 'BC'")

full_extend_ids = ax_full_extend_df["pt_root_id"].to_list()

ax_full_extend_df.iloc[0:40]

             pt_root_id cell_type_x        strategy_axon  strategy_dendrite
10   864691135741655956         23P  axon_fully_extended  dendrite_extended
36   864691136674080135         23P  axon_fully_extended  dendrite_extended
55   864691136110765496          MC  axon_fully_extended  dendrite_extended
63   864691135256861871       5P-IT  axon_fully_extended  dendrite_extended
66   864691136330122730       5P-IT  axon_fully_extended  dendrite_extended
83   864691135878061395       5P-IT  axon_fully_extended  dendrite_extended
139  864691135258083503         23P  axon_fully_extended     dendrite_clean
169  864691135890167433       5P-IT  axon_fully_extended  dendrite_extended
184  864691136974813212       5P-IT  axon_fully_extended  dendrite_extended
190  864691136445215875         23P  axon_fully_extended  dendrite_extended
207  864691136107603673       5P-IT  axon_fully_extended  dendrite_extended
223  864691135473692722         23P  axon_fully_extended  dendrite_extended
240  864691136674749575         23P  axon_fully_extended  dendrite_extended
244  864691136108071129         23P  axon_fully_extended  dendrite_extended
324  864691135430853424         23P  axon_fully_extended     dendrite_clean
342  864691135755308493       5P-IT  axon_fully_extended  dendrite_extended
345  864691136620192653          MC  axon_fully_extended  dendrite_extended
377  864691136953835487         23P  axon_fully_extended  dendrite_extended
404  864691136052828915          4P  axon_fully_extended  dendrite_extended
411  864691136196131542         23P  axon_fully_extended  dendrite_extended
414  864691135114178969       5P-IT  axon_fully_extended  dendrite_extended
419  864691135572346349       5P-IT  axon_fully_extended  dendrite_extended
421  864691135517376211       5P-PT  axon_fully_extended  dendrite_extended
448  864691135639556411       5P-IT  axon_fully_extended  dendrite_extended
452  864691135496268176         23P  axon_fully_extended  dendrite_extended
462  864691135760319822          4P  axon_fully_extended  dendrite_extended
487  864691136034011579         23P  axon_fully_extended  dendrite_extended
494  864691135356839887       5P-IT  axon_fully_extended  dendrite_extended
509  864691135308295238    Unsure E  axon_fully_extended  dendrite_extended
510  864691135720061233       5P-IT  axon_fully_extended  dendrite_extended
511  864691136238090767       5P-IT  axon_fully_extended     dendrite_clean
528  864691135430346544       5P-IT  axon_fully_extended  dendrite_extended
529  864691135339978214       5P-IT  axon_fully_extended  dendrite_extended
534  864691136086206316       5P-IT  axon_fully_extended  dendrite_extended
594  864691136040977662       5P-IT  axon_fully_extended  dendrite_extended
618  864691136991202453       5P-PT  axon_fully_extended  dendrite_extended
640  864691134886663674       5P-IT  axon_fully_extended  dendrite_extended
721  864691136335553971         23P  axon_fully_extended  dendrite_extended
728  864691135474179378          MC  axon_fully_extended  dendrite_extended
729  864691135479830982          4P  axon_fully_extended  dendrite_extended

In [4]:
all_full_extend_df = proof_df.query("strategy_axon == 'axon_fully_extended'")

#merge all_full_extend_df with cell_type_df on pt_root_id, left
all_full_extend_df = pd.merge(all_full_extend_df, cell_type_df, on='pt_root_id', how='left')

# all_full_extend_df = all_full_extend_df.query("cell_type != 'BC'") #remove all BC



all_full_extend_ids = all_full_extend_df["pt_root_id"].to_list()

# all_full_extend_df.iloc[0:40]

print(len(all_full_extend_ids))

# print(all_full_extend_ids[49:-1])

267

In [26]:
all_full_extend_df.iloc[200:250]

,pt_root_id,status_axon,status_dendrite,strategy_axon,strategy_dendrite,id_ref,created_ref,valid_ref,volume,pt_supervoxel_id,id,created,valid,target_id,classification_system,cell_type,pt_position,bb_start_position,bb_end_position
200,864691136453186559,t,t,axon_fully_extended,dendrite_extended,303115.0,2020-09-28 22:43:31.751462+00:00,t,356.344955,9.170923e+16,31288.0,2023-12-19 22:45:52.183540+00:00,t,303115.0,inhibitory_neuron,BC,"[195696, 200832, 21084]","[nan, nan, nan]","[nan, nan, nan]"
201,864691135442591048,t,t,axon_fully_extended,dendrite_extended,269557.0,2020-09-28 22:44:00.395171+00:00,t,201.339863,8.770021e+16,25915.0,2023-12-19 22:44:29.694326+00:00,t,269557.0,inhibitory_neuron,BC,"[166608, 215680, 23067]","[nan, nan, nan]","[nan, nan, nan]"
202,864691135989392387,t,t,axon_fully_extended,dendrite_extended,330372.0,2020-09-28 22:43:39.857212+00:00,t,365.302743,9.205551e+16,35325.0,2023-12-19 22:46:54.312499+00:00,t,330372.0,inhibitory_neuron,BC,"[198624, 159104, 21248]","[nan, nan, nan]","[nan, nan, nan]"
203,864691136011458734,t,t,axon_fully_extended,dendrite_extended,260575.0,2020-09-28 22:43:48.879799+00:00,t,365.960233,8.748154e+16,23512.0,2023-12-19 22:43:53.619432+00:00,t,260575.0,inhibitory_neuron,BC,"[164944, 159008, 21409]","[nan, nan, nan]","[nan, nan, nan]"
204,864691136274984638,t,t,axon_fully_extended,dendrite_extended,260824.0,2020-09-28 22:40:53.035083+00:00,t,323.171779,8.881834e+16,23624.0,2023-12-19 22:43:55.001389+00:00,t,260824.0,inhibitory_neuron,BC,"[174688, 157696, 23299]","[nan, nan, nan]","[nan, nan, nan]"
205,864691135760685390,t,t,axon_fully_extended,dendrite_extended,260672.0,2020-09-28 22:43:32.206822+00:00,t,347.295908,8.755129e+16,23557.0,2023-12-19 22:43:54.162211+00:00,t,260672.0,inhibitory_neuron,BC,"[165744, 154416, 22523]","[nan, nan, nan]","[nan, nan, nan]"
206,864691135702846075,t,t,axon_fully_extended,dendrite_extended,330650.0,2020-09-28 22:45:07.421935+00:00,t,321.153925,9.226559e+16,35411.0,2023-12-19 22:46:55.496291+00:00,t,330650.0,inhibitory_neuron,BC,"[199920, 151248, 23050]","[nan, nan, nan]","[nan, nan, nan]"
207,864691135106209101,t,t,axon_fully_extended,dendrite_extended,260206.0,2020-09-28 22:44:41.831013+00:00,t,274.336317,8.895778e+16,23419.0,2023-12-19 22:43:52.493949+00:00,t,260206.0,inhibitory_neuron,BC,"[175744, 148128, 19338]","[nan, nan, nan]","[nan, nan, nan]"
208,864691135388983425,t,t,axon_fully_extended,dendrite_extended,296421.0,2020-09-28 22:45:12.026726+00:00,t,337.884447,9.106884e+16,29346.0,2023-12-19 22:45:23.440856+00:00,t,296421.0,inhibitory_neuron,BC,"[191024, 147792, 19680]","[nan, nan, nan]","[nan, nan, nan]"
209,864691135499624723,t,t,axon_fully_extended,dendrite_extended,296378.0,2020-09-28 22:45:15.525967+00:00,t,349.033103,8.987243e+16,29326.0,2023-12-19 22:45:23.194192+00:00,t,296378.0,inhibitory_neuron,BC,"[182784, 146896, 19849]","[nan, nan, nan]","[nan, nan, nan]"
210,864691135209982841,t,t,axon_fully_extended,dendrite_extended,264635.0,2020-09-28 22:44:26.833086+00:00,t,252.722381,8.882212e+16,24765.0,2023-12-19 22:44:13.911178+00:00,t,264635.0,inhibitory_neuron,BC,"[175056, 185744, 19662]","[nan, nan, nan]","[nan, nan, nan]"
211,864691135102002720,t,t,axon_fully_extended,dendrite_extended,265129.0,2020-09-28 22:45:22.960984+00:00,t,405.801370,8.875148e+16,24895.0,2023-12-19 22:44:15.714064+00:00,t,265129.0,inhibitory_neuron,BC,"[174208, 183552, 23071]","[nan, nan, nan]","[nan, nan, nan]"
212,864691135920591792,t,t,axon_fully_extended,dendrite_extended,296580.0,2020-09-28 22:41:12.880113+00:00,t,345.259868,9.170188e+16,29403.0,2023-12-19 22:45:24.178545+00:00,t,296580.0,inhibitory_neuron,BC,"[196128, 145744, 21051]","[nan, nan, nan]","[nan, nan, nan]"
213,864691135405480430,t,t,axon_fully_extended,dendrite_extended,260777.0,2020-09-28 22:41:57.876827+00:00,t,278.693478,8.754985e+16,23601.0,2023-12-19 22:43:54.716441+00:00,t,260777.0,inhibitory_neuron,BC,"[165904, 143920, 23334]","[nan, nan, nan]","[nan, nan, nan]"
214,864691135784866867,t,t,axon_fully_extended,dendrite_extended,335367.0,2020-09-28 22:44:42.033449+00:00,t,274.903859,9.332586e+16,36654.0,2023-12-19 22:47:14.711110+00:00,t,335367.0,inhibitory_neuron,BC,"[207680, 186912, 20614]","[nan, nan, nan]","[nan, nan, nan]"
215,864691135732257721,t,t,axon_fully_extended,dendrite_extended,335638.0,2020-09-28 22:44:19.098366+00:00,t,240.376709,9.332586e+16,36744.0,2023-12-19 22:47:16.078350+00:00,t,335638.0,inhibitory_neuron,BC,"[207824, 186992, 22677]","[nan, nan, nan]","[nan, nan, nan]"
216,864691136177415430,t,t,axon_fully_extended,dendrite_extended,335310.0,2020-09-28 22:44:39.836706+00:00,t,271.112438,9.212980e+16,36635.0,2023-12-19 22:47:14.398390+00:00,t,335310.0,inhibitory_neuron,BC,"[198976, 188224, 20638]","[nan, nan, nan]","[nan, nan, nan]"
217,864691135388984961,t,t,axon_fully_extended,dendrite_extended,335669.0,2020-09-28 22:45:23.633082+00:00,t,432.523510,9.198927e+16,36756.0,2023-12-19 22:47:16.265456+00:00,t,335669.0,inhibitory_neuron,BC,"[197888, 189952, 23749]","[nan, nan, nan]","[nan, nan, nan]"
218,864691135384619738,t,t,axon_fully_extended,dendrite_extended,328518.0,2020-09-28 22:45:07.538187+00:00,t,321.755382,9.275611e+16,34764.0,2023-12-19 22:46:46.989224+00:00,t,328518.0,inhibitory_neuron,BC,"[203712, 136096, 22690]","[nan, nan, nan]","[nan, nan, nan]"
219,864691135134565280,t,t,axon_fully_extended,dendrite_extended,335691.0,2020-09-28 22:44:22.603705+00:00,t,245.662515,9.255167e+16,36767.0,2023-12-19 22:47:16.439461+00:00,t,335691.0,inhibitory_neuron,BC,"[202000, 185744, 23747]","[nan, nan, nan]","[nan, nan, nan]"
220,864691135499616019,t,t,axon_fully_extended,dendrite_extended,296579.0,2020-09-28 22:40:59.438131+00:00,t,335.921480,9.156307e+16,29402.0,2023-12-19 22:45:24.164452+00:00,t,296579.0,inhibitory_neuron,BC,"[195072, 160160, 20233]","[nan, nan, nan]","[nan, nan, nan]"
221,864691135375642824,t,t,axon_fully_extended,dendrite_extended,299010.0,2020-09-28 22:41:16.231654+00:00,t,388.396974,9.177417e+16,30146.0,2023-12-19 22:45:35.701608+00:00,t,299010.0,inhibitory_neuron,BC,"[196288, 160384, 21470]","[nan, nan, nan]","[nan, nan, nan]"
222,864691135685250546,t,t,axon_fully_extended,dendrite_extended,333180.0,2020-09-28 22:44:13.542334+00:00,t,230.272369,9.304088e+16,36094.0,2023-12-19 22:47:06.751234+00:00,t,333180.0,inhibitory_neuron,BC,"[205648, 160928, 22158]","[nan, nan, nan]","[nan, nan, nan]"
223,864691135778116013,t,t,axon_fully_extended,dendrite_extended,264875.0,2020-09-28 22:43:08.363290+00:00,t,355.857859,8.755432e+16,24815.0,2023-12-19 22:44:14.613403+00:00,t,264875.0,inhibitory_neuron,BC,"[165520, 177104, 21775]","[nan, nan, nan]","[nan, nan, nan]"
224,864691135469536652,t,t,axon_fully_extended,dendrite_extended,335201.0,2020-09-28 22:45:21.564340+00:00,t,395.730616,9.233939e+16,36603.0,2023-12-19 22:47:13.898341+00:00,t,335201.0,inhibitory_neuron,BC,"[200592, 176992, 20095]","[nan, nan, nan]","[nan, nan, nan]"
225,864691136742921308,t,t,axon_fully_extended,dendrite_extended,301473.0,2020-09-28 22:44:57.889203+00:00,t,302.613463,9.072105e+16,30894.0,2023-12-19 22:45:46.431969+00:00,t,301473.0,inhibitory_neuron,BC,"[188864, 178272, 24214]","[nan, nan, nan]","[nan, nan, nan]"
226,864691135492888039,t,t,axon_fully_extended,dendrite_extended,262567.0,2020-09-28 22:41:22.732788+00:00,t,298.918707,8.952423e+16,24156.0,2023-12-19 22:44:05.723560+00:00,t,262567.0,inhibitory_neuron,BC,"[180096, 173952, 19945]","[nan, nan, nan]","[nan, nan, nan]"
227,864691135891690121,t,t,axon_fully_extended,dendrite_extended,301374.0,2020-09-28 22:44:48.290613+00:00,t,285.581967,9.008807e+16,30850.0,2023-12-19 22:45:45.787016+00:00,t,301374.0,inhibitory_neuron,BC,"[184192, 180656, 23855]","[nan, nan, nan]","[nan, nan, nan]"
228,864691135885917808,t,t,axon_fully_extended,dendrite_extended,335604.0,2020-09-28 22:44:19.456853+00:00,t,241.431839,9.226950e+16,36727.0,2023-12-19 22:47:15.819165+00:00,t,335604.0,inhibitory_neuron,BC,"[199856, 180704, 22947]","[nan, nan, nan]","[nan, nan, nan]"
229,864691135442598728,t,t,axon_fully_extended,dendrite_extended,333364.0,2020-09-28 22:44:24.526412+00:00,t,248.517755,9.191629e+16,36150.0,2023-12-19 22:47:07.563516+00:00,t,333364.0,inhibitory_neuron,BC,"[197376, 170672, 23551]","[nan, nan, nan]","[nan, nan, nan]"
230,864691135810098717,t,t,axon_fully_extended,dendrite_extended,269452.0,2020-09-28 22:44:13.703656+00:00,t,230.958367,8.755940e+16,25881.0,2023-12-19 22:44:29.201907+00:00,t,269452.0,inhibitory_neuron,BC,"[165808, 214944, 22023]","[nan, nan, nan]","[nan, nan, nan]"
231,864691136120512792,t,t,axon_fully_extended,dendrite_extended,298531.0,2020-09-28 22:40:51.422017+00:00,t,356.290724,9.065013e+16,29999.0,2023-12-19 22:45:33.737864+00:00,t,298531.0,inhibitory_neuron,BC,"[188432, 173856, 19295]","[nan, nan, nan]","[nan, nan, nan]"
232,864691135448552532,t,t,axon_fully_extended,dendrite_extended,298759.0,2020-09-28 22:43:35.612802+00:00,t,365.420708,9.163481e+16,30052.0,2023-12-19 22:45:34.370612+00:00,t,298759.0,inhibitory_neuron,BC,"[195152, 170368, 19792]","[nan, nan, nan]","[nan, nan, nan]"
233,864691136312057178,t,t,axon_fully_extended,dendrite_extended,228276.0,2020-09-28 22:42:01.277126+00:00,t,305.013391,8.720172e+16,18315.0,2023-12-19 22:42:33.206808+00:00,t,228276.0,inhibitory_neuron,BC,"[163296, 171280, 21461]","[nan, nan, nan]","[nan, nan, nan]"
234,864691135738824580,t,t,axon_fully_extended,dendrite_extended,335338.0,2020-09-28 22:41:40.871131+00:00,t,320.370934,9.283245e+16,36646.0,2023-12-19 22:47:14.586951+00:00,t,335338.0,inhibitory_neuron,BC,"[204096, 180704, 21044]","[nan, nan, nan]","[nan, nan, nan]"
235,864691136523889553,t,t,axon_fully_extended,dendrite_extended,263169.0,2020-09-28 22:42:37.730867+00:00,t,324.373873,8.938246e+16,24359.0,2023-12-19 22:44:08.362595+00:00,t,263169.0,inhibitory_neuron,BC,"[178896, 166176, 24030]","[nan, nan, nan]","[nan, nan, nan]"
236,864691136742921820,t,t,axon_fully_extended,dendrite_extended,265231.0,2020-09-28 22:44:47.727124+00:00,t,283.593933,8.910305e+16,24934.0,2023-12-19 22:44:16.252434+00:00,t,265231.0,inhibitory_neuron,BC,"[176912, 181488, 23609]","[nan, nan, nan]","[nan, nan, nan]"
237,864691135702854011,t,t,axon_fully_extended,dendrite_extended,299317.0,2020-09-28 22:44:51.549031+00:00,t,290.239611,9.121150e+16,30265.0,2023-12-19 22:45:37.389289+00:00,t,299317.0,inhibitory_neuron,BC,"[192064, 162288, 23552]","[nan, nan, nan]","[nan, nan, nan]"
238,864691135106209869,t,t,axon_fully_extended,dendrite_extended,301375.0,2020-09-28 22:44:36.750798+00:00,t,267.881349,9.015858e+16,30851.0,2023-12-19 22:45:45.800150+00:00,t,301375.0,inhibitory_neuron,BC,"[184784, 181584, 23600]","[nan, nan, nan]","[nan, nan, nan]"
239,864691135586014328,t,t,axon_fully_extended,dendrite_extended,258457.0,2020-09-28 22:43:28.157717+00:00,t,397.885276,8.832267e+16,22944.0,2023-12-19 22:43:46.279937+00:00,t,258457.0,inhibitory_neuron,BC,"[171104, 134752, 23302]","[nan, nan, nan]","[nan, nan, nan]"
240,864691135941789606,t,t,axon_fully_extended,dendrite_extended,333268.0,2020-09-28 22:44:26.993840+00:00,t,253.229793,9.268952e+16,36123.0,2023-12-19 22:47:07.166317+00:00,t,333268.0,inhibitory_neuron,BC,"[202976, 164384, 22930]","[nan, nan, nan]","[nan, nan, nan]"
241,864691135928916180,t,t,axon_fully_extended,dendrite_extended,230507.0,2020-09-28 22:42:44.944431+00:00,t,429.243924,8.713293e+16,18916.0,2023-12-19 22:42:42.073120+00:00,t,230507.0,inhibitory_neuron,BC,"[162768, 183056, 21709]","[nan, nan, nan]","[nan, nan, nan]"
242,864691135741641876,t,t,axon_fully_extended,dendrite_extended,262427.0,2020-09-28 22:45:09.437781+00:00,t,327.180452,8.839702e+16,24129.0,2023-12-19 22:44:05.345859+00:00,t,262427.0,inhibitory_neuron,BC,"[171824, 164304, 19644]","[nan, nan, nan]","[nan, nan, nan]"
243,864691135912137641,t,t,axon_fully_extended,dendrite_extended,337814.0,2020-09-28 22:45:13.255532+00:00,t,340.045988,9.332772e+16,37196.0,2023-12-19 22:47:22.741986+00:00,t,337814.0,inhibitory_neuron,BC,"[207504, 200624, 21252]","[nan, nan, nan]","[nan, nan, nan]"
244,864691135990520064,t,t,axon_fully_extended,dendrite_extended,293058.0,2020-09-28 22:45:19.138473+00:00,t,368.444211,9.099387e+16,28297.0,2023-12-19 22:45:08.270137+00:00,t,293058.0,inhibitory_neuron,BC,"[190512, 113552, 23696]","[nan, nan, nan]","[nan, nan, nan]"
245,864691136313897789,t,t,axon_fully_extended,dendrite_extended,326322.0,2020-09-28 22:45:21.156817+00:00,t,385.904476,9.282359e+16,34101.0,2023-12-19 22:46:37.893193+00:00,t,326322.0,inhibitory_neuron,BC,"[203856, 114432, 21908]","[nan, nan, nan]","[nan, nan, nan]"
246,864691135405488366,t,t,axon_fully_extended,dendrite_extended,256505.0,2020-09-28 22:40:57.260670+00:00,t,286.056612,8.761651e+16,22252.0,2023-12-19 22:43:36.966788+00:00,t,256505.0,inhibitory_neuron,BC,"[166352, 116416, 21869]","[nan, nan, nan]","[nan, nan, nan]"
247,864691136007059658,t,t,axon_fully_extended,dendrite_extended,324332.0,2020-09-28 22:44:59.463384+00:00,t,305.284383,9.303332e+16,33530.0,2023-12-19 22:46:26.946125+00:00,t,324332.0,inhibitory_neuron,BC,"[205408, 104592, 22075]","[nan, nan, nan]","[nan, nan, nan]"
248,864691135375641288,t,t,axon_fully_extended,dendrite_extended,294935.0,2020-09-28 22:42:33.821119+00:00,t,270.448067,9.078668e+16,28908.0,2023-12-19 22:45:17.201487+00:00,t,294935.0,inhibitory_neuron,BC,"[189200, 143008, 23495]","[nan, nan, nan]","[nan, nan, nan]"
249,864691135566902615,t,t,axon_fully_extended,dendrite_extended,301335.0,2020-09-28 22:44:19.512414+00:00,t,241.616650,9.128400e+16,30831.0,2023-12-19 22:45:45.524315+00:00,t,301335.0,inhibitory_neuron,BC,"[192896, 177952, 23056]","[nan, nan, nan]","[nan, nan, nan]"

In [8]:
ax_full_extend_df.iloc[45:-1]

              pt_root_id cell_type_x        strategy_axon  strategy_dendrite
778   864691135655390658         23P  axon_fully_extended  dendrite_extended
808   864691135920571056          4P  axon_fully_extended  dendrite_extended
810   864691135701676411         23P  axon_fully_extended  dendrite_extended
832   864691136144674612         23P  axon_fully_extended  dendrite_extended
839   864691135646493679       5P-IT  axon_fully_extended  dendrite_extended
849   864691135350542039       5P-IT  axon_fully_extended  dendrite_extended
866   864691135346975135       5P-IT  axon_fully_extended  dendrite_extended
871   864691134886404090       5P-IT  axon_fully_extended  dendrite_extended
936   864691135891467401       5P-IT  axon_fully_extended  dendrite_extended
962   864691135325071004         23P  axon_fully_extended  dendrite_extended
976   864691135927533070       6P-IT  axon_fully_extended  dendrite_extended
979   864691135849300318       5P-IT  axon_fully_extended  dendrite_extended
982   864691135492613471         23P  axon_fully_extended  dendrite_extended
1000  864691135375767369       5P-IT  axon_fully_extended  dendrite_extended
1008  864691135572576237         23P  axon_fully_extended  dendrite_extended
1021  864691135361314119         23P  axon_fully_extended  dendrite_extended
1023  864691135163673901       5P-IT  axon_fully_extended  dendrite_extended
1026  864691135502748482       5P-IT  axon_fully_extended  dendrite_extended
1036  864691136053374451         23P  axon_fully_extended  dendrite_extended
1052  864691135614771147         23P  axon_fully_extended  dendrite_extended
1059  864691135464263742       5P-IT  axon_fully_extended  dendrite_extended
1074  864691136195284556          MC  axon_fully_extended  dendrite_extended
1075  864691136967478222       5P-IT  axon_fully_extended  dendrite_extended
1086  864691136725655037         23P  axon_fully_extended  dendrite_extended
1089  864691136238652476          MC  axon_fully_extended  dendrite_extended
1091  864691135356753871       5P-IT  axon_fully_extended  dendrite_extended
1093  864691136175901190       5P-IT  axon_fully_extended  dendrite_extended
1096  864691135988769027         23P  axon_fully_extended  dendrite_extended
1114  864691136093003700       5P-IT  axon_fully_extended  dendrite_extended
1127  864691135066631492       5P-IT  axon_fully_extended  dendrite_extended
1178  864691136042982742         23P  axon_fully_extended  dendrite_extended
1190  864691135970210661       5P-IT  axon_fully_extended  dendrite_extended
1193  864691136380757461       5P-IT  axon_fully_extended  dendrite_extended
1204  864691135476495936          4P  axon_fully_extended  dendrite_extended
1205  864691135572082925          MC  axon_fully_extended  dendrite_extended
1206  864691136195889622         23P  axon_fully_extended  dendrite_extended
1209  864691135726140843          4P  axon_fully_extended  dendrite_extended
1221  864691135274038801         23P  axon_fully_extended  dendrite_extended
1235  864691136664845278         23P  axon_fully_extended  dendrite_extended
1241  864691136674495623       5P-IT  axon_fully_extended  dendrite_extended
1250  864691135430356784       5P-IT  axon_fully_extended  dendrite_extended
1263  864691135954021923       5P-IT  axon_fully_extended  dendrite_extended
1265  864691135566237527         23P  axon_fully_extended  dendrite_extended
1269  864691135617152361       5P-IT  axon_fully_extended  dendrite_extended
1273  864691135938604804         23P  axon_fully_extended  dendrite_extended
1281  864691135777521837         23P  axon_fully_extended  dendrite_extended
1296  864691136210743740       5P-IT  axon_fully_extended  dendrite_extended
1316  864691135778700477         23P  axon_fully_extended  dendrite_extended
1329  864691135503182685       5P-PT  axon_fully_extended  dendrite_extended
1330  864691136335150259       5P-PT  axon_fully_extended  dendrite_extended

In [7]:
importlib.reload(myelin_extraction) #delete this later....

classifier_model = SimpleClassifier()
model_weights_file = "DNN_classifiers/myelin_classifier_v0_1.pt"
max_workers=23 #i like 23
box_sz_microns = "adaptive"
length_thresh=3000 #3000 is default.

#72...

#115

#go back to 105....

myelin_extraction.process_neurons(all_full_extend_ids[137:-1], client, img_client, classifier_model, model_weights_file, max_workers, box_sz_microns, length_thresh)

# myelin_extraction.process_neurons([864691136033871035], client, img_client, classifier_model, model_weights_file, max_workers, box_sz_microns, length_thresh)

File segments_myelin_1507/864691135375430985.pkl already exists. Skipping neuron 864691135375430985.
File segments_myelin_1507/864691135927533070.pkl already exists. Skipping neuron 864691135927533070.
File segments_myelin_1507/864691136086206316.pkl already exists. Skipping neuron 864691136086206316.
File segments_myelin_1507/864691135196040746.pkl already exists. Skipping neuron 864691135196040746.
File segments_myelin_1507/864691136363828194.pkl already exists. Skipping neuron 864691136363828194.
File segments_myelin_1507/864691135954021923.pkl already exists. Skipping neuron 864691135954021923.
File segments_myelin_1507/864691135988769027.pkl already exists. Skipping neuron 864691135988769027.
File segments_myelin_1507/864691135572576237.pkl already exists. Skipping neuron 864691135572576237.
File segments_myelin_1507/864691136445215875.pkl already exists. Skipping neuron 864691136445215875.
File segments_myelin_1507/864691135464263742.pkl already exists. Skipping neuron 864691135464263742.
File segments_myelin_1507/864691134886404090.pkl already exists. Skipping neuron 864691134886404090.
File segments_myelin_1507/864691136620195213.pkl already exists. Skipping neuron 864691136620195213.
File segments_myelin_1507/864691136579127060.pkl already exists. Skipping neuron 864691136579127060.
File segments_myelin_1507/864691136110765496.pkl already exists. Skipping neuron 864691136110765496.
File segments_myelin_1507/864691135517376211.pkl already exists. Skipping neuron 864691135517376211.
File segments_myelin_1507/864691135503182685.pkl already exists. Skipping neuron 864691135503182685.
File segments_myelin_1507/864691135569282284.pkl already exists. Skipping neuron 864691135569282284.
File segments_myelin_1507/864691135464714565.pkl already exists. Skipping neuron 864691135464714565.
File segments_myelin_1507/864691135492613471.pkl already exists. Skipping neuron 864691135492613471.
File segments_myelin_1507/864691136974813212.pkl already exists. Skipping neuron 864691136974813212.
File segments_myelin_1507/864691136991202453.pkl already exists. Skipping neuron 864691136991202453.
File segments_myelin_1507/864691135446065810.pkl already exists. Skipping neuron 864691135446065810.
File segments_myelin_1507/864691135577202181.pkl already exists. Skipping neuron 864691135577202181.
File segments_myelin_1507/864691136137140093.pkl already exists. Skipping neuron 864691136137140093.
File segments_myelin_1507/864691135273655569.pkl already exists. Skipping neuron 864691135273655569.
File segments_myelin_1507/864691134886037498.pkl already exists. Skipping neuron 864691134886037498.
File segments_myelin_1507/864691136175901190.pkl already exists. Skipping neuron 864691136175901190.
File segments_myelin_1507/864691135492614239.pkl already exists. Skipping neuron 864691135492614239.
File segments_myelin_1507/864691136966189518.pkl already exists. Skipping neuron 864691136966189518.
File segments_myelin_1507/864691135118298333.pkl already exists. Skipping neuron 864691135118298333.
File segments_myelin_1507/864691135639556411.pkl already exists. Skipping neuron 864691135639556411.
File segments_myelin_1507/864691135489514810.pkl already exists. Skipping neuron 864691135489514810.
File segments_myelin_1507/864691135114295961.pkl already exists. Skipping neuron 864691135114295961.
File segments_myelin_1507/864691135404765166.pkl already exists. Skipping neuron 864691135404765166.
File segments_myelin_1507/864691136974876956.pkl already exists. Skipping neuron 864691136974876956.
File segments_myelin_1507/864691136335150259.pkl already exists. Skipping neuron 864691136335150259.
File segments_myelin_1507/864691136578820884.pkl already exists. Skipping neuron 864691136578820884.
File segments_myelin_1507/864691135492804327.pkl already exists. Skipping neuron 864691135492804327.
File segments_myelin_1507/864691135878061395.pkl already exists. Skipping neuron 864691135878061395.
File segments_myelin_1507/864691135430853424.pkl already exists. Skipping neuron 864691135430853424.
File segments_myelin_1507/864691135526405723.pkl already exists. Skipping neuron 864691135526405723.
File segments_myelin_1507/864691136040977662.pkl already exists. Skipping neuron 864691136040977662.
Processing neuron 864691135811260876
Starting segment 1/611
Processed point: [124564 154984  23307]: Myelin=0.0
Processed point: [126540 156360  23422]: Myelin=0.0
Processed point: [128266 157514  23549]: Myelin=0.0
Processed point: [126948 156590  23442]: Myelin=0.0
Processed point: [128536 157896  23585]: Myelin=0.0
Processed point: [127725 157072  23490]: Myelin=0.0
Processed point: [125076 155318  23342]: Myelin=0.0
Processed point: [124184 154655  23263]: Myelin=0.0
Processed point: [127356 156820  23463]: Myelin=0.0
Processed point: [128418 157836  23571]: Myelin=0.0
Processed point: [125368 155438  23368]: Myelin=0.0
Processed point: [128920 158532  23649]: Myelin=0.0
Processed point: [123938 154218  23201]: Myelin=0.0
Processed point: [123878 154304  23216]: Myelin=0.0
Processed point: [129298 158646  23681]: Myelin=0.0
Processed point: [125992 155698  23395]: Myelin=0.0
Processed point: [127418 156906  23465]: Myelin=0.0
Processed point: [126496 156360  23419]: Myelin=0.0
Processed point: [123896 154360  23224]: Myelin=0.0
Processed point: [130676 159810  23781]: Myelin=0.0
Processed point: [123938 154392  23229]: Myelin=0.0
Processed point: [129938 158828  23707]: Myelin=0.0
Processed point: [131868 160678  23860]: Myelin=0.0
Processed point: [128112 157276  23526]: Myelin=0.0
Processed point: [126384 156252  23408]: Myelin=0.0
Processed point: [125912 155654  23393]: Myelin=0.0
Processed point: [124430 154918  23297]: Myelin=0.0
Processed point: [128032 157238  23516]: Myelin=0.0
Processed point: [130450 159686  23762]: Myelin=0.0
Processed point: [132766 161248  23882]: Myelin=0.0
Processed point: [128788 158214  23626]: Myelin=0.0
Processed point: [130932 160046  23811]: Myelin=0.0
Processed point: [130242 159092  23732]: Myelin=0.0
Processed point: [130050 158958  23716]: Myelin=0.0
Processed point: [131450 160438  23840]: Myelin=0.0
Processed point: [132342 160936  23859]: Myelin=0.0
Processed point: [131500 160524  23844]: Myelin=0.0
Processed point: [133544 161620  23960]: Myelin=0.0
Processed point: [132394 161018  23857]: Myelin=0.0
Processed point: [133138 161478  23907]: Myelin=0.0
Processed point: [133174 161578  23922]: Myelin=0.0
Processed point: [135228 162502  24062]: Myelin=0.0
Processed point: [133128 161480  23913]: Myelin=0.0
Processed point: [135280 162540  24063]: Myelin=0.0
Processed point: [133914 161662  23998]: Myelin=0.0
Processed point: [135540 162754  24073]: Myelin=0.0
Processed point: [134642 162036  24042]: Myelin=0.0
Processed point: [135830 163010  24082]: Myelin=0.0
Processed point: [134994 162304  24057]: Myelin=0.0
Processed point: [134326 161732  24016]: Myelin=0.0
Finished segment 1/611 for neuron 864691135811260876
Time per point: 0.25 seconds
Starting segment 2/611
Processed point: [125390 164040  22931]: Myelin=0.0
Processed point: [125696 164274  22944]: Myelin=0.0
Processed point: [127790 165230  22969]: Myelin=0.0
Processed point: [124192 163270  22920]: Myelin=0.0
Processed point: [124684 163526  22916]: Myelin=0.0
Processed point: [126814 164482  22958]: Myelin=0.0
Processed point: [124774 163624  22918]: Myelin=0.0
Processed point: [123828 162224  22847]: Myelin=0.0
Processed point: [126126 164200  22962]: Myelin=0.0
Processed point: [123870 163100  22908]: Myelin=0.0
Processed point: [129902 167278  23072]: Myelin=0.0
Processed point: [129888 167012  23071]: Myelin=0.0
Processed point: [129426 166422  23072]: Myelin=0.0
Processed point: [129562 166600  23070]: Myelin=0.0
Processed point: [125186 163934  22919]: Myelin=0.0
Processed point: [128646 165990  23035]: Myelin=0.0
Processed point: [130640 168526  23212]: Myelin=0.0
Processed point: [130570 167664  23192]: Myelin=0.0
Processed point: [128850 166144  23041]: Myelin=0.0
Processed point: [128090 165498  22989]: Myelin=0.0
Processed point: [127548 165062  22965]: Myelin=0.0
Processed point: [130514 168222  23214]: Myelin=0.0
Processed point: [128940 166222  23042]: Myelin=0.0
Processed point: [130586 167948  23206]: Myelin=0.0
Processed point: [130594 167898  23206]: Myelin=0.0
Processed point: [123938 162298  22798]: Myelin=0.0
Processed point: [130826 168870  23202]: Myelin=0.0
Processed point: [131170 169158  23197]: Myelin=0.0
Processed point: [130404 167542  23153]: Myelin=0.0
Processed point: [128266 165766  23009]: Myelin=0.0
Processed point: [126810 164578  22959]: Myelin=0.0
Processed point: [123754 162616  22881]: Myelin=0.0
Processed point: [130238 167420  23115]: Myelin=0.0
Processed point: [127200 164834  22966]: Myelin=0.0
Finished segment 2/611 for neuron 864691135811260876
Time per point: 0.36 seconds
Starting segment 3/611
Processed point: [127764 170291  23177]: Myelin=0.0
Processed point: [128530 169600  23143]: Myelin=0.0
Processed point: [128000 170008  23187]: Myelin=0.0
Processed point: [127476 170594  23164]: Myelin=0.0
Processed point: [128684 169526  23130]: Myelin=0.0
Processed point: [127528 170574  23168]: Myelin=0.0
Processed point: [128122 169868  23184]: Myelin=0.0
Finished segment 3/611 for neuron 864691135811260876
Time per point: 0.66 seconds
Starting segment 4/611
Processed point: [130780 164464  21100]: Myelin=0.0
Error processing point [132867 165178  21251]: min() arg is an empty sequence
Processed point: [132867 165178  21251]: Myelin=-1
Processed point: [128074 163444  21027]: Myelin=0.0
Processed point: [130368 164408  21098]: Myelin=0.0
Processed point: [131058 164568  21102]: Myelin=0.0
Processed point: [128512 163778  21030]: Myelin=0.0
Processed point: [127616 161848  21088]: Myelin=0.0
Processed point: [129132 164358  21074]: Myelin=0.0
Processed point: [132250 164838  21159]: Myelin=0.0
Processed point: [129056 164330  21070]: Myelin=0.0
Processed point: [128580 163854  21033]: Myelin=0.0
Processed point: [133054 165306  21288]: Myelin=0.0
Processed point: [129780 164550  21109]: Myelin=0.0
Processed point: [128818 164092  21051]: Myelin=0.0
Processed point: [127872 162985  21025]: Myelin=0.0
Processed point: [127954 163356  21022]: Myelin=0.0
Processed point: [127624 162266  21058]: Myelin=0.0
Processed point: [132680 165050  21215]: Myelin=0.0
Processed point: [127790 162614  21028]: Myelin=0.0
Processed point: [129526 164552  21084]: Myelin=0.0
Processed point: [131882 164854  21129]: Myelin=0.0
Processed point: [129716 164592  21107]: Myelin=0.0
Processed point: [133446 165165  21341]: Myelin=0.0
Processed point: [131260 164764  21100]: Myelin=0.0
Processed point: [134088 165200  21398]: Myelin=0.0
Processed point: [139442 166440  21487]: Myelin=0.0
Processed point: [134508 165334  21419]: Myelin=0.0
Processed point: [139654 166638  21500]: Myelin=0.0
Processed point: [140610 167058  21591]: Myelin=0.0
Processed point: [135948 165846  21436]: Myelin=0.0
Processed point: [140210 166924  21560]: Myelin=0.0
Processed point: [137504 166150  21448]: Myelin=0.0
Processed point: [136450 166036  21447]: Myelin=0.0
Processed point: [137368 166086  21449]: Myelin=0.0
Processed point: [140960 167064  21628]: Myelin=0.0
Processed point: [138468 166224  21462]: Myelin=0.0
Processed point: [134712 165400  21430]: Myelin=0.0
Processed point: [135340 165534  21442]: Myelin=0.0
Processed point: [141636 167386  21692]: Myelin=0.0
Processed point: [135368 165578  21440]: Myelin=0.0
Processed point: [141176 167190  21641]: Myelin=0.0
Processed point: [138146 166238  21451]: Myelin=0.0
Processed point: [136918 165904  21458]: Myelin=0.0
Processed point: [133668 165066  21378]: Myelin=0.0
Processed point: [139808 166794  21525]: Myelin=0.0
Processed point: [133224 165264  21305]: Myelin=0.0
Processed point: [139036 166172  21473]: Myelin=0.0
Processed point: [139810 166790  21529]: Myelin=0.0
Processed point: [141938 167550  21734]: Myelin=0.0
Processed point: [142250 167855  21771]: Myelin=0.0
Processed point: [141982 167716  21742]: Myelin=0.0
Processed point: [145584 167920  22050]: Myelin=0.0
Processed point: [143564 167938  21943]: Myelin=0.0
Processed point: [144000 167758  21983]: Myelin=0.0
Processed point: [142518 167994  21801]: Myelin=0.0
Processed point: [142861 167944  21847]: Myelin=0.0
Processed point: [143204 167894  21894]: Myelin=0.0
Processed point: [145034 168086  22037]: Myelin=0.0
Processed point: [144928 168032  22029]: Myelin=0.0
Processed point: [144622 167968  21990]: Myelin=0.0
Finished segment 4/611 for neuron 864691135811260876
Time per point: 0.34 seconds
Starting segment 5/611
Processed point: [129120 168208  23057]: Myelin=0.0
Processed point: [129132 168864  23056]: Myelin=0.0
Processed point: [128829 167511  23047]: Myelin=0.0
Processed point: [128572 167110  23053]: Myelin=0.0
Processed point: [128536 167106  23053]: Myelin=0.0
Processed point: [128602 167190  23052]: Myelin=0.0
Processed point: [129056 167832  23043]: Myelin=0.0
Processed point: [129168 167864  23042]: Myelin=0.0
Finished segment 5/611 for neuron 864691135811260876
Time per point: 0.79 seconds
Starting segment 6/611
Processed point: [130478 169610  23174]: Myelin=0.0
Processed point: [130998 169292  23191]: Myelin=0.0
Processed point: [129326 169348  23104]: Myelin=0.0
Processed point: [129716 169794  23129]: Myelin=0.0
Processed point: [130220 169742  23162]: Myelin=0.0
Processed point: [129664 169670  23127]: Myelin=0.0
Finished segment 6/611 for neuron 864691135811260876
Time per point: 0.94 seconds
Starting segment 7/611
Processed point: [130848 169274  23306]: Myelin=0.0
Processed point: [130477 169472  23324]: Myelin=0.0
Processed point: [131356 169162  23274]: Myelin=0.0
Processed point: [130070 169736  23345]: Myelin=0.0
Processed point: [130100 169714  23344]: Myelin=0.0
Processed point: [130106 169670  23342]: Myelin=0.0
Finished segment 7/611 for neuron 864691135811260876
Time per point: 0.40 seconds
Starting segment 8/611
Processed point: [131873 167015  24203]: Myelin=0.0
Processed point: [131409 167332  24238]: Myelin=0.0
Processed point: [132242 166312  24212]: Myelin=0.0
Processed point: [130602 167112  24376]: Myelin=0.0
Processed point: [130722 167104  24306]: Myelin=0.0
Processed point: [130594 167180  24326]: Myelin=0.0
Processed point: [132640 165572  24227]: Myelin=0.0
Processed point: [131108 167310  24272]: Myelin=0.0
Processed point: [132578 165676  24226]: Myelin=0.0
Processed point: [131710 167354  24205]: Myelin=0.0
Processed point: [131104 167316  24273]: Myelin=0.0
Processed point: [130562 166968  24385]: Myelin=0.0
Processed point: [133216 165102  24226]: Myelin=0.0
Processed point: [133086 165082  24232]: Myelin=0.0
Processed point: [130594 167078  24342]: Myelin=0.0
Processed point: [132064 166552  24206]: Myelin=0.0
Processed point: [132036 166676  24202]: Myelin=0.0
Processed point: [130594 166978  24379]: Myelin=0.0
Finished segment 8/611 for neuron 864691135811260876
Time per point: 0.36 seconds
Starting segment 9/611
Processed point: [131632 169206  23224]: Myelin=0.0
Processed point: [131286 169204  23205]: Myelin=0.0
Finished segment 9/611 for neuron 864691135811260876
Time per point: 0.53 seconds
Starting segment 10/611
Processed point: [131978 169208  23243]: Myelin=0.0
Processed point: [132642 169160  23234]: Myelin=0.0
Processed point: [132904 169146  23235]: Myelin=0.0
Processed point: [134426 168904  23258]: Myelin=1.0
Processed point: [136217 168742  23254]: Myelin=0.0
Processed point: [138750 169007  23260]: Myelin=0.0
Processed point: [137416 168932  23249]: Myelin=0.0
Processed point: [133458 169144  23226]: Myelin=0.0
Processed point: [132188 169230  23246]: Myelin=0.0
Processed point: [133800 169070  23223]: Myelin=1.0
Processed point: [136678 168810  23247]: Myelin=0.0
Processed point: [134944 168726  23265]: Myelin=0.0
Processed point: [139528 169194  23258]: Myelin=0.0
Processed point: [139240 169164  23266]: Myelin=0.0
Processed point: [139120 169130  23264]: Myelin=0.0
Processed point: [135500 168604  23268]: Myelin=0.0
Processed point: [135756 168674  23261]: Myelin=0.0
Processed point: [138380 168884  23257]: Myelin=0.0
Processed point: [138126 168862  23256]: Myelin=1.0
Processed point: [135232 168648  23267]: Myelin=0.0
Processed point: [140210 169160  23253]: Myelin=0.0
Processed point: [136922 168822  23253]: Myelin=0.0
Processed point: [141094 169068  23272]: Myelin=0.0
Processed point: [140320 169158  23253]: Myelin=0.0
Processed point: [135644 168648  23267]: Myelin=0.0
Processed point: [140450 169082  23257]: Myelin=0.0
Finished segment 10/611 for neuron 864691135811260876
Time per point: 0.41 seconds
Starting segment 11/611
Processed point: [133680 163008  24226]: Myelin=0.0
Processed point: [133586 164524  24230]: Myelin=0.0
Processed point: [133508 164176  24246]: Myelin=0.0
Processed point: [133744 163272  24236]: Myelin=0.0
Processed point: [133666 163670  24246]: Myelin=0.0
Processed point: [133600 163806  24248]: Myelin=0.0
Processed point: [133484 162760  24207]: Myelin=0.0
Finished segment 11/611 for neuron 864691135811260876
Time per point: 0.40 seconds
Starting segment 12/611
Processed point: [135260 163644  24076]: Myelin=0.0
Processed point: [135180 163938  24083]: Myelin=0.0
Processed point: [133664 164872  24215]: Myelin=0.0
Processed point: [133718 164874  24211]: Myelin=0.0
Processed point: [135474 163406  24074]: Myelin=0.0
Processed point: [134310 165062  24175]: Myelin=0.0
Processed point: [134460 165108  24161]: Myelin=0.0
Processed point: [135086 164166  24096]: Myelin=0.0
Processed point: [134688 164970  24133]: Myelin=0.0
Processed point: [134838 164768  24125]: Myelin=0.0
Finished segment 12/611 for neuron 864691135811260876
Time per point: 0.28 seconds
Starting segment 13/611
Processed point: [139358 159192  23205]: Myelin=0.0
Processed point: [138008 157506  23071]: Myelin=0.0
Processed point: [138255 157629  23099]: Myelin=0.0
Processed point: [139344 158882  23196]: Myelin=0.0
Processed point: [137758 157312  23045]: Myelin=0.0
Processed point: [137762 157384  23043]: Myelin=0.0
Processed point: [138748 157874  23155]: Myelin=0.0
Processed point: [137370 156756  23030]: Myelin=0.0
Processed point: [138501 157751  23127]: Myelin=0.0
Processed point: [138786 157892  23158]: Myelin=0.0
Processed point: [139206 158626  23190]: Myelin=0.0
Processed point: [137626 157086  23035]: Myelin=0.0
Processed point: [135036 156764  23015]: Myelin=0.0
Processed point: [136482 156466  22977]: Myelin=0.0
Processed point: [139450 159662  23236]: Myelin=0.0
Processed point: [135026 156872  23010]: Myelin=0.0
Processed point: [137808 157356  23048]: Myelin=0.0
Processed point: [136830 156546  22984]: Myelin=0.0
Processed point: [139554 160336  23261]: Myelin=0.0
Processed point: [136070 156370  22989]: Myelin=0.0
Processed point: [135372 156606  22997]: Myelin=0.0
Processed point: [139030 158042  23172]: Myelin=0.0
Finished segment 13/611 for neuron 864691135811260876
Time per point: 0.34 seconds
Starting segment 14/611
Processed point: [136404 174622  24060]: Myelin=0.0
Processed point: [136094 174496  24063]: Myelin=0.0
Processed point: [137744 173590  24072]: Myelin=0.0
Processed point: [137824 173382  24076]: Myelin=0.0
Processed point: [135714 174486  24066]: Myelin=0.0
Processed point: [135496 174448  24066]: Myelin=0.0
Processed point: [135062 174538  24095]: Myelin=0.0
Processed point: [137348 174792  24105]: Myelin=0.0
Processed point: [138224 173148  24082]: Myelin=0.0
Processed point: [138740 173422  24126]: Myelin=1.0
Processed point: [137690 174110  24066]: Myelin=0.0
Processed point: [137598 174506  24080]: Myelin=0.0
Processed point: [138298 173168  24087]: Myelin=0.0
Processed point: [136694 174790  24086]: Myelin=0.0
Processed point: [136710 174874  24086]: Myelin=0.0
Processed point: [136738 174896  24087]: Myelin=0.0
Finished segment 14/611 for neuron 864691135811260876
Time per point: 0.39 seconds

KeyboardInterrupt:

In [19]:
#Extracting partially extended neurons.

ax_part_extend_df = proof_df.query("strategy_axon == 'axon_partially_extended'")
ax_part_extend_pt_root_ids = ax_part_extend_df['pt_root_id'].values

#filter for cell type == 4P
ax_part_extend_df = pd.merge(ax_part_extend_df, cell_type_df, on='pt_root_id', how='left')
ax_part_extend_df = ax_part_extend_df.query("cell_type == '4P'")
ax_part_extend_pt_root_ids = ax_part_extend_df['pt_root_id'].values

classifier_model = SimpleClassifier()
model_weights_file = "DNN_classifiers/myelin_classifier_v0_1.pt"
max_workers=17 #i like 23
box_sz_microns = "adaptive"
length_thresh=3000 #3000 is default.


myelin_extraction.process_neurons(ax_part_extend_pt_root_ids[15:-1], client, img_client, classifier_model, model_weights_file, max_workers, box_sz_microns, length_thresh)

File segments_myelin_1507/864691135742189163.pkl already exists. Skipping neuron 864691135742189163.
File segments_myelin_1507/864691136025333561.pkl already exists. Skipping neuron 864691136025333561.
Processing neuron 864691135101521952
Starting segment 1/45
Processed point: [151962 204316  23561]: Myelin=0.0
Processed point: [154426 202984  23442]: Myelin=0.0
Processed point: [154008 203096  23477]: Myelin=0.0
Processed point: [154594 202950  23426]: Myelin=0.0
Processed point: [154926 202760  23415]: Myelin=0.0
Processed point: [150758 205000  23560]: Myelin=0.0
Processed point: [152364 204056  23553]: Myelin=0.0
Processed point: [149012 205850  23626]: Myelin=0.0
Processed point: [150106 205534  23573]: Myelin=0.0
Processed point: [153168 203518  23540]: Myelin=0.0
Processed point: [155202 202504  23403]: Myelin=0.0
Processed point: [151792 204698  23565]: Myelin=0.0
Processed point: [150854 204950  23559]: Myelin=0.0
Processed point: [150372 205420  23563]: Myelin=0.0
Processed point: [152532 203906  23549]: Myelin=1.0
Processed point: [153538 203256  23520]: Myelin=0.0
Processed point: [152890 203836  23551]: Myelin=0.0
Processed point: [155950 201382  23302]: Myelin=0.0
Processed point: [151274 204906  23568]: Myelin=0.0
Processed point: [156572 200796  23283]: Myelin=0.0
Processed point: [152190 204148  23554]: Myelin=0.0
Processed point: [157018 200594  23288]: Myelin=0.0
Processed point: [157154 200330  23294]: Myelin=0.0
Processed point: [157570 200080  23263]: Myelin=0.0
Processed point: [156428 201030  23298]: Myelin=0.0
Processed point: [155846 201564  23324]: Myelin=0.0
Processed point: [157788 199980  23282]: Myelin=0.0
Processed point: [155552 201726  23369]: Myelin=0.0
Processed point: [149280 205770  23603]: Myelin=0.0
Processed point: [155248 202282  23389]: Myelin=0.0
Processed point: [149858 205630  23577]: Myelin=0.0
Finished segment 1/45 for neuron 864691135101521952
Time per point: 0.46 seconds
Starting segment 2/45
Processed point: [151110 145058  21975]: Myelin=0.0
Processed point: [153018 148928  22059]: Myelin=0.0
Processed point: [151738 146222  22010]: Myelin=0.0
Processed point: [152054 146680  22028]: Myelin=0.0
Processed point: [153324 149272  22080]: Myelin=0.0
Processed point: [152148 146800  22034]: Myelin=0.0
Processed point: [152584 147168  22057]: Myelin=0.0
Processed point: [152812 148410  22046]: Myelin=0.0
Processed point: [155452 152466  22167]: Myelin=0.0
Processed point: [153124 149182  22074]: Myelin=0.0
Processed point: [151310 145402  21980]: Myelin=0.0
Error processing point [155260 151453  22143]: min() arg is an empty sequence
Processed point: [155260 151453  22143]: Myelin=-1
Processed point: [154644 150264  22113]: Myelin=0.0
Processed point: [154326 150102  22109]: Myelin=0.0
Processed point: [154030 149896  22106]: Myelin=0.0
Processed point: [152740 147858  22037]: Myelin=0.0
Processed point: [151650 145982  21984]: Myelin=0.0
Processed point: [155086 150882  22141]: Myelin=0.0
Processed point: [155772 154214  22244]: Myelin=0.0
Processed point: [155548 153954  22238]: Myelin=0.0
Processed point: [156212 155334  22245]: Myelin=0.0
Processed point: [155990 154686  22240]: Myelin=0.0
Processed point: [151542 145748  21986]: Myelin=0.0
Processed point: [151984 146458  22018]: Myelin=0.0
Processed point: [155434 152024  22146]: Myelin=0.0
Processed point: [150772 144850  21966]: Myelin=0.0
Processed point: [156042 154824  22243]: Myelin=0.0
Processed point: [152670 147532  22054]: Myelin=0.0
Processed point: [155646 153512  22210]: Myelin=0.0
Processed point: [157638 156414  22273]: Myelin=0.0
Processed point: [157344 156266  22254]: Myelin=0.0
Processed point: [153668 149582  22109]: Myelin=0.0
Processed point: [155460 153016  22192]: Myelin=0.0
Processed point: [156818 155768  22253]: Myelin=0.0
Processed point: [156448 155392  22252]: Myelin=0.0
Processed point: [157112 156072  22250]: Myelin=0.0
Processed point: [154770 150382  22119]: Myelin=0.0
Finished segment 2/45 for neuron 864691135101521952
Time per point: 0.48 seconds
Starting segment 3/45
Processed point: [156128 175066  24773]: Myelin=0.0
Processed point: [155682 178582  24731]: Myelin=0.0
Processed point: [155170 181056  24700]: Myelin=0.0
Processed point: [156194 175222  24777]: Myelin=0.0
Processed point: [155906 176532  24760]: Myelin=0.0
Processed point: [156256 175492  24783]: Myelin=0.0
Processed point: [156192 175798  24772]: Myelin=0.0
Processed point: [155112 181312  24693]: Myelin=1.0
Processed point: [155762 178166  24729]: Myelin=0.0
Processed point: [155570 179710  24730]: Myelin=0.0
Processed point: [154620 182460  24638]: Myelin=0.0
Processed point: [155706 179464  24740]: Myelin=0.0
Processed point: [155262 180676  24726]: Myelin=0.0
Processed point: [155020 181688  24671]: Myelin=0.0
Processed point: [154574 182520  24639]: Myelin=0.0
Processed point: [155830 177480  24734]: Myelin=0.0
Processed point: [156052 174676  24770]: Myelin=0.0
Processed point: [155776 179162  24740]: Myelin=0.0
Processed point: [154760 182218  24625]: Myelin=0.0
Processed point: [154336 183534  24624]: Myelin=0.0
Processed point: [153318 185884  24567]: Myelin=0.0
Processed point: [153564 185476  24594]: Myelin=0.0
Processed point: [154262 183160  24622]: Myelin=0.0
Processed point: [155404 180154  24743]: Myelin=0.0
Processed point: [153504 185658  24589]: Myelin=0.0
Processed point: [156092 176252  24769]: Myelin=0.0
Processed point: [155770 177086  24733]: Myelin=0.0
Processed point: [154376 183940  24618]: Myelin=0.0
Processed point: [153210 186314  24516]: Myelin=0.0
Processed point: [153386 186862  24529]: Myelin=0.0
Processed point: [153218 187304  24497]: Myelin=0.0
Processed point: [152944 187732  24512]: Myelin=0.0
Processed point: [152980 187540  24493]: Myelin=0.0
Processed point: [154104 184936  24604]: Myelin=0.0
Processed point: [153832 185256  24596]: Myelin=0.0
Processed point: [154416 184346  24613]: Myelin=0.0
Processed point: [152562 189098  24454]: Myelin=0.0
Processed point: [154244 184638  24601]: Myelin=0.0
Processed point: [153388 192968  24347]: Myelin=0.0
Processed point: [152670 192336  24380]: Myelin=1.0
Processed point: [152586 192296  24390]: Myelin=0.0
Processed point: [152282 191124  24437]: Myelin=0.0
Processed point: [153560 193280  24317]: Myelin=0.0
Processed point: [153994 193493  24257]: Myelin=0.0
Processed point: [153690 193356  24299]: Myelin=0.0
Processed point: [152610 188280  24487]: Myelin=0.0
Processed point: [154562 193984  24170]: Myelin=0.0
Processed point: [154298 193630  24216]: Myelin=0.0
Processed point: [153144 192680  24366]: Myelin=0.0
Processed point: [155890 194992  24010]: Myelin=0.0
Processed point: [152178 190004  24441]: Myelin=0.0
Processed point: [152224 191486  24451]: Myelin=0.0
Processed point: [157130 195712  23946]: Myelin=0.0
Processed point: [152215 190755  24440]: Myelin=0.0
Processed point: [152148 190386  24443]: Myelin=0.0
Processed point: [156450 195180  23995]: Myelin=0.0
Processed point: [155290 194654  24056]: Myelin=0.0
Processed point: [152436 191964  24427]: Myelin=0.0
Processed point: [157512 197554  23711]: Myelin=0.0
Processed point: [155548 194830  24036]: Myelin=0.0
Processed point: [154978 194474  24096]: Myelin=0.0
Processed point: [157380 197076  23740]: Myelin=0.0
Processed point: [157900 198110  23630]: Myelin=0.0
Processed point: [155186 194664  24066]: Myelin=0.0
Processed point: [156704 195298  23987]: Myelin=0.0
Processed point: [157848 197678  23681]: Myelin=0.0
Processed point: [154658 194122  24148]: Myelin=0.0
Processed point: [152380 189542  24453]: Myelin=0.0
Processed point: [152632 188936  24463]: Myelin=0.0
Processed point: [157216 196306  23852]: Myelin=0.0
Processed point: [157244 196478  23830]: Myelin=0.0
Processed point: [157834 198824  23453]: Myelin=0.0
Processed point: [157864 198966  23485]: Myelin=0.0
Processed point: [158026 199214  23366]: Myelin=0.0
Processed point: [157930 199019  23409]: Myelin=0.0
Processed point: [157780 198756  23525]: Myelin=0.0
Processed point: [157312 196777  23785]: Myelin=0.0
Processed point: [157090 196022  23887]: Myelin=0.0
Processed point: [157782 198386  23608]: Myelin=0.0
Processed point: [157638 198518  23583]: Myelin=0.0
Processed point: [157984 199391  23327]: Myelin=0.0
Processed point: [157778 198690  23563]: Myelin=0.0
Finished segment 3/45 for neuron 864691135101521952
Time per point: 0.35 seconds
Starting segment 4/45
Processed point: [188984 136422  23298]: Myelin=0.0
Processed point: [191540 133350  23062]: Myelin=0.0
Processed point: [191008 133802  23130]: Myelin=0.0
Processed point: [189672 135438  23236]: Myelin=0.0
Processed point: [190272 134830  23213]: Myelin=0.0
Processed point: [188158 137022  23326]: Myelin=0.0
Processed point: [187802 137264  23348]: Myelin=0.0
Processed point: [190688 134220  23162]: Myelin=0.0
Processed point: [187476 137458  23354]: Myelin=0.0
Processed point: [187126 137714  23372]: Myelin=0.0
Processed point: [191520 132738  23055]: Myelin=0.0
Processed point: [188506 136940  23319]: Myelin=0.0
Processed point: [190584 134378  23185]: Myelin=0.0
Processed point: [189836 135204  23229]: Myelin=0.0
Processed point: [188742 136748  23311]: Myelin=0.0
Processed point: [191600 133054  23056]: Myelin=0.0
Processed point: [186482 138552  23420]: Myelin=0.0
Processed point: [191298 133562  23081]: Myelin=0.0
Processed point: [186082 139098  23443]: Myelin=0.0
Processed point: [186306 138794  23434]: Myelin=0.0
Processed point: [185586 139632  23449]: Myelin=0.0
Processed point: [185114 140094  23422]: Myelin=0.0
Processed point: [186990 137994  23389]: Myelin=0.0
Processed point: [185244 139868  23435]: Myelin=0.0
Processed point: [189326 135776  23266]: Myelin=0.0
Processed point: [184418 140584  23374]: Myelin=0.0
Processed point: [190176 134906  23217]: Myelin=0.0
Processed point: [184174 140692  23355]: Myelin=0.0
Processed point: [191556 132780  23055]: Myelin=0.0
Processed point: [183886 141084  23343]: Myelin=0.0
Processed point: [185806 139392  23449]: Myelin=0.0
Processed point: [183840 141312  23335]: Myelin=0.0
Processed point: [189178 136084  23281]: Myelin=0.0
Processed point: [186634 138234  23411]: Myelin=0.0
Processed point: [183450 141562  23326]: Myelin=0.0
Processed point: [183108 141858  23305]: Myelin=0.0
Processed point: [182376 142616  23279]: Myelin=0.0
Processed point: [184736 140400  23398]: Myelin=0.0
Processed point: [182840 142038  23305]: Myelin=0.0
Processed point: [182012 142890  23246]: Myelin=0.0
Processed point: [181336 143592  23171]: Myelin=0.0
Processed point: [180516 144344  23121]: Myelin=0.0
Processed point: [181456 143488  23197]: Myelin=0.0
Processed point: [182664 142288  23294]: Myelin=0.0
Processed point: [180030 144376  23086]: Myelin=0.0
Processed point: [181838 143078  23242]: Myelin=0.0
Processed point: [179626 144520  23077]: Myelin=0.0
Processed point: [179316 144794  23082]: Myelin=0.0
Processed point: [179180 144796  23057]: Myelin=0.0
Processed point: [181144 143992  23148]: Myelin=0.0
Processed point: [178066 146028  23057]: Myelin=0.0
Processed point: [177378 146768  23034]: Myelin=0.0
Processed point: [176452 147522  22993]: Myelin=0.0
Processed point: [178472 145886  23058]: Myelin=1.0
Processed point: [175756 148200  22969]: Myelin=0.0
Processed point: [177696 146468  23042]: Myelin=0.0
Processed point: [177776 146354  23051]: Myelin=0.0
Processed point: [180902 144138  23137]: Myelin=0.0
Processed point: [178570 145434  23058]: Myelin=1.0
Processed point: [177660 146524  23041]: Myelin=0.0
Processed point: [174990 148632  22915]: Myelin=0.0
Processed point: [176006 148086  22978]: Myelin=0.0
Processed point: [174540 148856  22894]: Myelin=0.0
Processed point: [175284 148508  22935]: Myelin=0.0
Processed point: [173926 149354  22869]: Myelin=0.0
Processed point: [173602 149704  22868]: Myelin=0.0
Processed point: [178792 145240  23060]: Myelin=0.0
Processed point: [173312 149960  22866]: Myelin=0.0
Processed point: [171986 151120  22823]: Myelin=0.0
Processed point: [171502 151488  22809]: Myelin=0.0
Processed point: [171224 151848  22809]: Myelin=0.0
Processed point: [174734 148736  22903]: Myelin=0.0
Processed point: [173138 150254  22857]: Myelin=0.0
Processed point: [172306 150848  22834]: Myelin=0.0
Processed point: [171616 151440  22804]: Myelin=0.0
Processed point: [170790 152088  22794]: Myelin=0.0
Processed point: [170438 152604  22779]: Myelin=0.0
Processed point: [170706 152346  22791]: Myelin=0.0
Processed point: [174136 149214  22878]: Myelin=0.0
Processed point: [172898 150492  22847]: Myelin=0.0
Processed point: [172654 150768  22832]: Myelin=0.0
Processed point: [169216 153538  22695]: Myelin=0.0
Processed point: [168044 154408  22678]: Myelin=0.0
Processed point: [167714 154540  22695]: Myelin=0.0
Processed point: [167250 154816  22688]: Myelin=0.0
Processed point: [166658 155176  22677]: Myelin=0.0
Processed point: [169602 153344  22730]: Myelin=0.0
Processed point: [169900 153250  22748]: Myelin=0.0
Processed point: [170150 153052  22768]: Myelin=0.0
Processed point: [168426 153766  22681]: Myelin=0.0
Processed point: [167174 154824  22685]: Myelin=0.0
Processed point: [168684 153636  22688]: Myelin=0.0
Processed point: [166406 155286  22671]: Myelin=0.0
Processed point: [165336 155804  22649]: Myelin=0.0
Processed point: [165660 155638  22664]: Myelin=0.0
Processed point: [164968 155944  22633]: Myelin=0.0
Processed point: [163016 155452  22557]: Myelin=0.0
Processed point: [162676 155574  22552]: Myelin=0.0
Processed point: [164860 155846  22634]: Myelin=0.0
Processed point: [161808 155638  22530]: Myelin=0.0
Processed point: [166086 155420  22675]: Myelin=0.0
Processed point: [161524 155616  22524]: Myelin=0.0
Processed point: [164433 155716  22608]: Myelin=0.0
Processed point: [168190 154006  22675]: Myelin=0.0
Processed point: [163652 155516  22567]: Myelin=0.0
Processed point: [164006 155586  22582]: Myelin=0.0
Processed point: [164866 155848  22634]: Myelin=0.0
Processed point: [159030 155556  22369]: Myelin=0.0
Processed point: [160388 155589  22408]: Myelin=0.0
Processed point: [160000 155478  22394]: Myelin=0.0
Processed point: [158634 155660  22356]: Myelin=0.0
Processed point: [158396 156040  22309]: Myelin=0.0
Processed point: [158198 156268  22303]: Myelin=0.0
Processed point: [160776 155700  22423]: Myelin=0.0
Processed point: [159552 155400  22384]: Myelin=0.0
Processed point: [162140 155550  22543]: Myelin=0.0
Processed point: [161006 155618  22474]: Myelin=0.0
Processed point: [176890 147246  23020]: Myelin=0.0
Processed point: [176276 147736  22998]: Myelin=0.0
Processed point: [177176 147130  23025]: Myelin=0.0
Finished segment 4/45 for neuron 864691135101521952
Time per point: 0.75 seconds
Starting segment 5/45
Processed point: [158240 156922  22289]: Myelin=0.0
Processed point: [159596 158502  22301]: Myelin=0.0
Processed point: [161956 160752  22322]: Myelin=0.0
Processed point: [161304 159980  22297]: Myelin=0.0
Processed point: [159946 158846  22285]: Myelin=0.0
Processed point: [157988 156574  22281]: Myelin=0.0
Processed point: [158538 157500  22313]: Myelin=0.0
Processed point: [160514 159172  22279]: Myelin=0.0
Processed point: [158386 157208  22293]: Myelin=0.0
Processed point: [159384 158316  22306]: Myelin=0.0
Processed point: [158814 157810  22310]: Myelin=0.0
Processed point: [158988 158074  22303]: Myelin=0.0
Processed point: [160214 158988  22280]: Myelin=1.0
Processed point: [161690 160422  22311]: Myelin=0.0
Processed point: [162596 162274  22291]: Myelin=0.0
Processed point: [161746 160472  22314]: Myelin=0.0
Processed point: [162966 162310  22292]: Myelin=0.0
Processed point: [160898 159376  22273]: Myelin=0.0
Processed point: [162418 161796  22288]: Myelin=0.0
Processed point: [163462 163476  22293]: Myelin=0.0
Processed point: [163060 162756  22300]: Myelin=0.0
Processed point: [160876 159524  22280]: Myelin=0.0
Processed point: [162212 161188  22312]: Myelin=0.0
Processed point: [164420 165034  22286]: Myelin=0.0
Processed point: [163190 163186  22306]: Myelin=0.0
Processed point: [162358 161420  22296]: Myelin=0.0
Processed point: [163872 164184  22304]: Myelin=0.0
Processed point: [164988 166530  22268]: Myelin=0.0
Processed point: [165428 167056  22254]: Myelin=0.0
Processed point: [165946 167606  22247]: Myelin=0.0
Processed point: [163942 164514  22310]: Myelin=0.0
Processed point: [166374 168178  22250]: Myelin=0.0
Processed point: [164500 165190  22285]: Myelin=0.0
Processed point: [166146 167798  22249]: Myelin=0.0
Processed point: [164166 164682  22300]: Myelin=0.0
Processed point: [164648 165520  22269]: Myelin=0.0
Processed point: [164838 166378  22269]: Myelin=0.0
Processed point: [167386 169444  22234]: Myelin=0.0
Processed point: [167162 169004  22241]: Myelin=0.0
Processed point: [165778 167486  22249]: Myelin=0.0
Processed point: [163624 163816  22303]: Myelin=0.0
Processed point: [166884 168708  22247]: Myelin=0.0
Processed point: [164796 165850  22254]: Myelin=0.0
Processed point: [166536 168256  22245]: Myelin=0.0
Processed point: [167502 169602  22235]: Myelin=0.0
Processed point: [168812 170736  22265]: Myelin=0.0
Processed point: [168068 170102  22248]: Myelin=0.0
Processed point: [168338 170426  22249]: Myelin=0.0
Processed point: [165360 166776  22263]: Myelin=0.0
Processed point: [170780 171894  22252]: Myelin=0.0
Processed point: [167620 170180  22241]: Myelin=0.0
Processed point: [171512 172270  22224]: Myelin=0.0
Processed point: [169188 170894  22285]: Myelin=0.0
Processed point: [170388 171744  22263]: Myelin=0.0
Processed point: [170156 171664  22278]: Myelin=0.0
Processed point: [169634 171118  22283]: Myelin=0.0
Processed point: [168616 170546  22252]: Myelin=0.0
Processed point: [169748 171236  22282]: Myelin=0.0
Processed point: [171888 172772  22204]: Myelin=0.0
Processed point: [173394 173352  22183]: Myelin=0.0
Processed point: [174520 173792  22144]: Myelin=0.0
Processed point: [176136 174804  22078]: Myelin=0.0
Processed point: [171830 172696  22205]: Myelin=0.0
Processed point: [175550 174488  22113]: Myelin=0.0
Processed point: [175266 174164  22122]: Myelin=0.0
Processed point: [176650 175320  22095]: Myelin=0.0
Processed point: [172280 172900  22200]: Myelin=0.0
Processed point: [171370 172114  22226]: Myelin=0.0
Processed point: [176390 174934  22080]: Myelin=0.0
Processed point: [174956 173928  22133]: Myelin=0.0
Processed point: [172872 173104  22192]: Myelin=0.0
Processed point: [173056 173294  22186]: Myelin=0.0
Processed point: [173824 173648  22159]: Myelin=0.0
Processed point: [175952 174690  22088]: Myelin=0.0
Processed point: [174304 173720  22147]: Myelin=0.0
Processed point: [179604 176080  22134]: Myelin=0.0
Processed point: [180792 176838  22156]: Myelin=0.0
Processed point: [180616 176486  22143]: Myelin=0.0
Processed point: [176926 175540  22103]: Myelin=0.0
Processed point: [180132 176356  22135]: Myelin=0.0
Processed point: [177210 175754  22112]: Myelin=0.0
Processed point: [181392 177542  22177]: Myelin=0.0
Processed point: [181922 177824  22179]: Myelin=0.0
Processed point: [182520 178086  22175]: Myelin=0.0
Processed point: [177854 176016  22119]: Myelin=1.0
Processed point: [178878 175866  22135]: Myelin=0.0
Processed point: [178426 175922  22136]: Myelin=0.0
Processed point: [183528 179684  22181]: Myelin=0.0
Processed point: [183236 178984  22184]: Myelin=0.0
Processed point: [179794 176208  22133]: Myelin=0.0
Error processing point [179241 175973  22134]: min() arg is an empty sequence
Processed point: [179241 175973  22134]: Myelin=-1
Processed point: [182876 178696  22183]: Myelin=0.0
Processed point: [180948 177140  22172]: Myelin=0.0
Processed point: [181254 177402  22178]: Myelin=0.0
Processed point: [182084 177916  22178]: Myelin=0.0
Processed point: [177580 175888  22114]: Myelin=0.0
Processed point: [183374 179208  22182]: Myelin=1.0
Processed point: [182792 178498  22180]: Myelin=0.0

KeyboardInterrupt:

In [10]:
#Extracting partially extended neurons with a focus on the ones projecting to hva.

with open('ax_partially_extended_but_interareal.pkl', 'rb') as f:
    pt_root_ids = pickle.load(f)

classifier_model = SimpleClassifier()
model_weights_file = "DNN_classifiers/myelin_classifier_v0_1.pt"
max_workers=25 #i like 23
box_sz_microns = "adaptive"
length_thresh=3000 #3000 is default.

# reverse pt_root_ids list, so it starts from the end.
pt_root_ids = pt_root_ids[::-1]


myelin_extraction.process_neurons(pt_root_ids[40:-1], client, img_client, classifier_model, model_weights_file, max_workers, box_sz_microns, length_thresh)

File segments_myelin_1507/864691135469924178.pkl already exists. Skipping neuron 864691135469924178.
File segments_myelin_1507/864691136380268245.pkl already exists. Skipping neuron 864691136380268245.
File segments_myelin_1507/864691136380795861.pkl already exists. Skipping neuron 864691136380795861.
File segments_myelin_1507/864691135778465376.pkl already exists. Skipping neuron 864691135778465376.
File segments_myelin_1507/864691135309141062.pkl already exists. Skipping neuron 864691135309141062.
File segments_myelin_1507/864691136135997579.pkl already exists. Skipping neuron 864691136135997579.
File segments_myelin_1507/864691135725838763.pkl already exists. Skipping neuron 864691135725838763.
File segments_myelin_1507/864691136380816597.pkl already exists. Skipping neuron 864691136380816597.
File segments_myelin_1507/864691135214653240.pkl already exists. Skipping neuron 864691135214653240.
File segments_myelin_1507/864691135209715577.pkl already exists. Skipping neuron 864691135209715577.
File segments_myelin_1507/864691135271282085.pkl already exists. Skipping neuron 864691135271282085.
File segments_myelin_1507/864691136618553563.pkl already exists. Skipping neuron 864691136618553563.
File segments_myelin_1507/864691135417236410.pkl already exists. Skipping neuron 864691135417236410.
File segments_myelin_1507/864691135867644805.pkl already exists. Skipping neuron 864691135867644805.
File segments_myelin_1507/864691135271696549.pkl already exists. Skipping neuron 864691135271696549.
File segments_myelin_1507/864691136195566294.pkl already exists. Skipping neuron 864691136195566294.
File segments_myelin_1507/864691136177029382.pkl already exists. Skipping neuron 864691136177029382.
File segments_myelin_1507/864691135396115189.pkl already exists. Skipping neuron 864691135396115189.
File segments_myelin_1507/864691135503798965.pkl already exists. Skipping neuron 864691135503798965.
File segments_myelin_1507/864691135060094107.pkl already exists. Skipping neuron 864691135060094107.
File segments_myelin_1507/864691136905458866.pkl already exists. Skipping neuron 864691136905458866.
File segments_myelin_1507/864691136195798504.pkl already exists. Skipping neuron 864691136195798504.
File segments_myelin_1507/864691135384176602.pkl already exists. Skipping neuron 864691135384176602.
File segments_myelin_1507/864691135885663600.pkl already exists. Skipping neuron 864691135885663600.
File segments_myelin_1507/864691135105897037.pkl already exists. Skipping neuron 864691135105897037.
File segments_myelin_1507/864691136419797655.pkl already exists. Skipping neuron 864691136419797655.
File segments_myelin_1507/864691136927176778.pkl already exists. Skipping neuron 864691136927176778.
File segments_myelin_1507/864691134966005023.pkl already exists. Skipping neuron 864691134966005023.
File segments_myelin_1507/864691135970653797.pkl already exists. Skipping neuron 864691135970653797.
File segments_myelin_1507/864691136742244188.pkl already exists. Skipping neuron 864691136742244188.
File segments_myelin_1507/864691135106110285.pkl already exists. Skipping neuron 864691135106110285.
File segments_myelin_1507/864691135810803660.pkl already exists. Skipping neuron 864691135810803660.
File segments_myelin_1507/864691135571192966.pkl already exists. Skipping neuron 864691135571192966.
File segments_myelin_1507/864691137055326070.pkl already exists. Skipping neuron 864691137055326070.
File segments_myelin_1507/864691135988649219.pkl already exists. Skipping neuron 864691135988649219.
File segments_myelin_1507/864691134966324767.pkl already exists. Skipping neuron 864691134966324767.
File segments_myelin_1507/864691135585713528.pkl already exists. Skipping neuron 864691135585713528.
File segments_myelin_1507/864691135640865083.pkl already exists. Skipping neuron 864691135640865083.
File segments_myelin_1507/864691136311451226.pkl already exists. Skipping neuron 864691136311451226.
File segments_myelin_1507/864691135519105930.pkl already exists. Skipping neuron 864691135519105930.
File segments_myelin_1507/864691135941293057.pkl already exists. Skipping neuron 864691135941293057.
File segments_myelin_1507/864691136914031601.pkl already exists. Skipping neuron 864691136914031601.
File segments_myelin_1507/864691135941435393.pkl already exists. Skipping neuron 864691135941435393.
File segments_myelin_1507/864691135499283987.pkl already exists. Skipping neuron 864691135499283987.
File segments_myelin_1507/864691135809509917.pkl already exists. Skipping neuron 864691135809509917.
File segments_myelin_1507/864691136664308446.pkl already exists. Skipping neuron 864691136664308446.
File segments_myelin_1507/864691136579629844.pkl already exists. Skipping neuron 864691136579629844.
File segments_myelin_1507/864691135868957462.pkl already exists. Skipping neuron 864691135868957462.
File segments_myelin_1507/864691135546339880.pkl already exists. Skipping neuron 864691135546339880.
File segments_myelin_1507/864691135014860278.pkl already exists. Skipping neuron 864691135014860278.
File segments_myelin_1507/864691135760106830.pkl already exists. Skipping neuron 864691135760106830.
File segments_myelin_1507/864691135688186080.pkl already exists. Skipping neuron 864691135688186080.
File segments_myelin_1507/864691135741458324.pkl already exists. Skipping neuron 864691135741458324.
Processing neuron 864691135801267554
Starting segment 1/68

KeyboardInterrupt:

864691135476495936 - i like this neuron.

caffeinate -i -t 259200